services:
  dicom-api:
    container_name: pycad-api
    build: .
    ports:
      - "8501:8501"         
    networks:
      - infraestructura_app-network
    restart: unless-stopped
    environment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ctscan.rule=Host(`ctscan.sintaq.net`)"
      - "traefik.http.routers.ctscan.entrypoints=websecure"
      - "traefik.http.routers.ctscan.tls=true"
      - "traefik.http.routers.ctscan.tls.certresolver=cloudflare"
      - "traefik.http.services.ctscan.loadbalancer.server.port=8501"
    volumes:
networks:
  infraestructura_app-network:
    external: true